CREATE TABLE actors (
  id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  name VARCHAR(250),
  name_original VARCHAR (250),
  photo VARCHAR (250),
  CONSTRAINT actor_key PRIMARY KEY (id)
);
