CREATE TABLE film_genres (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  film_id INTEGER,
  genre_id INTEGER,
  CONSTRAINT film_id_ref2 FOREIGN KEY (film_id) REFERENCES FILMS(id),
  CONSTRAINT genre_id_ref FOREIGN KEY (genre_id) REFERENCES GENRES(id)
);
