CREATE TABLE film_tags (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  film_id INTEGER,
  tag_id INTEGER,
  CONSTRAINT film_id_ref3 FOREIGN KEY (film_id) REFERENCES FILMS(id),
  CONSTRAINT tag_id_ref FOREIGN KEY (tag_id) REFERENCES TAGS(id)
);
