CREATE TABLE film_seasons (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR,
  description VARCHAR,
  path VARCHAR,
  film_id INTEGER,
  CONSTRAINT film_id_ref4 FOREIGN KEY (film_id) REFERENCES FILMS(id)
);